### ISSUE TITLE
If I "minimize" camelus and restore it after some time, the feed doesn't update automatically

### ISSUE THREAD

**Issue by bitcoinuser** [leo-lox/camelus#50]
Hi,

If I "minimize" camelus and restore it after some time, the feed doesn't update automatically. I need to close and reopen camelus to the feed update.

Thanks.

**Comment by bitcoinuser** [comment]
Maybe pulldown to refresh should be used to reconnect and update the feed.

**Comment by 1-leo** [comment]
hey thx for trying out camelus!
Its a knwn issue and related to our nostr ndk https://github.com/relaystr/ndk it will be fixed in the main release.
I added a public bug tracker for better communication, but feel free to report as issues i will then triage them.
https://github.com/users/leo-lox/projects/3/views/1
